package com.aura.app.navigation

object Routes {
    const val ONBOARDING = "onboarding"
    const val HOME = "home"
    const val FAVORITES = "favorites"
    const val CHATS = "chats"
    const val REWARDS = "rewards"
    const val PROFILE = "profile"
    const val SETTINGS = "settings"
    const val SETTINGS_NOTIFICATIONS = "settings_notifications"
    const val SETTINGS_APPEARANCE = "settings_appearance"
    const val SETTINGS_SECURITY = "settings_security"
    const val SETTINGS_PRIVACY = "settings_privacy"
    const val CREATE_LISTING = "place_ad_category"
    const val PLACE_AD_TYPE = "place_ad_type/{category}"
    const val PLACE_AD_UPLOAD = "place_ad_upload"
    const val PLACE_AD_LOCATION = "place_ad_location"
    const val LISTING_DETAIL = "listing_detail/{listingId}"
    const val CHAT_DETAIL = "chat_detail/{listingId}"
    const val MEET_SESSION = "meet_session"
    const val VERIFY_ITEM = "verify_item"
    const val ESCROW_PAY = "escrow_pay"

    const val TRADE_COMPLETE = "trade_complete"
    const val FACE_VERIFICATION = "face_verification"
    const val AURA_CHECK = "aura_check"
    const val P2P_EXCHANGE = "p2p_exchange"
    const val ZONE_REFINEMENT = "zone_refinement"
    const val DIRECTIVES = "directives"

    fun listingDetail(listingId: String) = "listing_detail/$listingId"
    fun chatDetail(listingId: String) = "chat_detail/$listingId"
    fun placeAdType(category: String) = "place_ad_type/$category"
}
