package com.aura.app.navigation

object Routes {
    const val ONBOARDING = "onboarding"
    const val HOME = "home"
    const val CHATS = "chats"
    const val REWARDS = "rewards"
    const val PROFILE = "profile"
    const val SETTINGS = "settings"
    const val SETTINGS_NOTIFICATIONS = "settings_notifications"
    const val SETTINGS_APPEARANCE = "settings_appearance"
    const val SETTINGS_SECURITY = "settings_security"
    const val SETTINGS_PRIVACY = "settings_privacy"
    const val CREATE_LISTING = "place_ad_category"
    const val PLACE_AD_TYPE = "place_ad_type/{category}"
    const val PLACE_AD_UPLOAD = "place_ad_upload"
    const val PLACE_AD_LOCATION = "place_ad_location"
    const val LISTING_DETAIL = "listing_detail/{listingId}"
    const val CHAT_DETAIL = "chat_detail/{listingId}"
    const val MEET_LOCATION = "meet_location/{listingId}"
    const val MEET_SESSION = "meet_session"
    const val VERIFY_ITEM = "verify_item"
    const val ESCROW_PAY = "escrow_pay"

    const val TRADE_COMPLETE = "trade_complete"
    const val FACE_VERIFICATION = "face_verification"
    const val AURA_CHECK = "aura_check"
    const val P2P_EXCHANGE = "p2p_exchange"
    const val ZONE_REFINEMENT = "zone_refinement"
    const val DIRECTIVES = "directives"
    const val MISSION_DETAIL = "mission_detail"
    const val SECURITY = "security"
    const val PRIVACY = "privacy"
    // Phase 2: Avatar + Store
    const val AVATAR_CREATOR = "avatar_creator"
    const val AVATAR_STORE   = "avatar_store"
    const val EMIRATE_PICKER = "emirate_picker"

    fun listingDetail(listingId: String) = "listing_detail/$listingId"
    fun meetLocation(listingId: String) = "meet_location/$listingId"
    fun chatDetail(listingId: String) = "chat_detail/$listingId"
    fun placeAdType(category: String) = "place_ad_type/$category"
}
